/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class StartInterface extends javax.swing.JFrame {
    public static String heuristic;
    public static String algorithm;
    public static String goal;

    /**
     * Creates new form UDPPeer1
     */
    public StartInterface() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    //This function is a timer that specifies the time of showing the notification.
    private void callTimer(JFrame notification) {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                notification.setVisible(false);
            }
        }, 6000);
    }
    
    //This function receives a message and displays it on a notification.
    private void displayNotification(String message) {
        Notification error = new Notification();
        error.setText(message);
        error.setVisible(true);
        callTimer(error);
    }


    //Function to replace the button with another one with a different color.
    private void scaleimage__replaceButton(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }
    
    //A Function to make the label's background white when the mouse is entered.
    public void scaleimage__backcwhite(JLabel label, String path) {
        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        label.setIcon(scaledIcon);
    }

    //A Function to return the label's original background when the mouse is exited.
    public void scaleimage__backc_white_remove(JLabel label) {
        ImageIcon icon = new ImageIcon("");
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
       label.setIcon(scaledIcon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbl_Logo = new javax.swing.JLabel();
        jLbl_Title = new javax.swing.JLabel();
        jLbl_UpBar = new javax.swing.JLabel();
        jComboBox_Heuristic = new javax.swing.JComboBox<>();
        jComboBox_Algorithm = new javax.swing.JComboBox<>();
        jComboBox_GoalPoint = new javax.swing.JComboBox<>();
        jLbl_Play = new javax.swing.JLabel();
        jLbl_ReturnBack = new javax.swing.JLabel();
        jLbl_robotGIF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("8-Puzzle Game");
        setIconImage(new ImageIcon("src\\Images\\Logo Mersal.png").getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLbl_Logo.setFont(new java.awt.Font("Script MT Bold", 1, 17)); // NOI18N
        jLbl_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jPanel1.add(jLbl_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 70, 70));

        jLbl_Title.setFont(new java.awt.Font("Century Gothic", 3, 45)); // NOI18N
        jLbl_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLbl_Title.setText("8 - Puzzle");
        jPanel1.add(jLbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 250, 70));

        jLbl_UpBar.setBackground(new java.awt.Color(38, 50, 54));
        jLbl_UpBar.setOpaque(true);
        jPanel1.add(jLbl_UpBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jComboBox_Heuristic.setBackground(new java.awt.Color(255, 255, 255,0));
        jComboBox_Heuristic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_Heuristic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Heuristic", "In Place", "Manhattan Distance" }));
        jComboBox_Heuristic.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jComboBox_Heuristic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_HeuristicActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_Heuristic, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, 40));

        jComboBox_Algorithm.setBackground(new java.awt.Color(255, 255, 255,0));
        jComboBox_Algorithm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_Algorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose an Algorithm", "Greedy Algorithm", "A* Algorithm" }));
        jComboBox_Algorithm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jComboBox_Algorithm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 280, 40));

        jComboBox_GoalPoint.setBackground(new java.awt.Color(255, 255, 255,0));
        jComboBox_GoalPoint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_GoalPoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Goal", "Circular Clockwise", "Row-Major Order" }));
        jComboBox_GoalPoint.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        jPanel1.add(jComboBox_GoalPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 280, 40));

        jLbl_Play.setFont(new java.awt.Font("Zilla Slab SemiBold", 0, 24)); // NOI18N
        jLbl_Play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Play.setText("Play");
        jLbl_Play.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(38, 50, 54)));
        jLbl_Play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLbl_Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_PlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_PlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_PlayMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 150, 50));

        jLbl_ReturnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BlackBack.png"))); // NOI18N
        jLbl_ReturnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbl_ReturnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbl_ReturnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbl_ReturnBackMouseExited(evt);
            }
        });
        jPanel1.add(jLbl_ReturnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 35, 28));

        jLbl_robotGIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/robotStart.gif"))); // NOI18N
        jPanel1.add(jLbl_robotGIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 620, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbl_PlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_PlayMouseExited
        // TODO add your handling code here:
        scaleimage__backc_white_remove(jLbl_Play);
        jLbl_Play.setForeground(Color.black);
    }//GEN-LAST:event_jLbl_PlayMouseExited

    private void jLbl_PlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_PlayMouseEntered
        // TODO add your handling code here:
        scaleimage__backcwhite(jLbl_Play, "src\\Images\\Gray.PNG");
        jLbl_Play.setForeground(new Color(38,50,54));
    }//GEN-LAST:event_jLbl_PlayMouseEntered

    private void jLbl_PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_PlayMouseClicked
        // TODO add your handling code here:
        if(jComboBox_Heuristic.getSelectedItem().toString().equals("Choose a Heuristic") ||
           jComboBox_Algorithm.getSelectedItem().toString().equals("Choose an Algorithm") ||
           jComboBox_GoalPoint.getSelectedItem().toString().equals("Choose a Goal")) {
            displayNotification("Please make sure that all fields are selected!");
        }
        //Store which heuristic, algorithm, and goal were selected by the user.
        else {
            heuristic = jComboBox_Heuristic.getSelectedItem().toString();
            algorithm = jComboBox_Algorithm.getSelectedItem().toString();
            goal = jComboBox_GoalPoint.getSelectedItem().toString();

            new BoardInterface().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLbl_PlayMouseClicked

    private void jLbl_ReturnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_ReturnBackMouseClicked
        new MainInterface().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLbl_ReturnBackMouseClicked

    private void jLbl_ReturnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_ReturnBackMouseEntered
        scaleimage__backcwhite(jLbl_ReturnBack, "src\\Images\\GrayBack.png");
    }//GEN-LAST:event_jLbl_ReturnBackMouseEntered

    private void jLbl_ReturnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbl_ReturnBackMouseExited
        scaleimage__replaceButton(jLbl_ReturnBack, "src\\Images\\BlackBack.png");
    }//GEN-LAST:event_jLbl_ReturnBackMouseExited

    private void jComboBox_HeuristicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_HeuristicActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_HeuristicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_Algorithm;
    private javax.swing.JComboBox<String> jComboBox_GoalPoint;
    private javax.swing.JComboBox<String> jComboBox_Heuristic;
    private javax.swing.JLabel jLbl_Logo;
    private javax.swing.JLabel jLbl_Play;
    private javax.swing.JLabel jLbl_ReturnBack;
    private javax.swing.JLabel jLbl_Title;
    private javax.swing.JLabel jLbl_UpBar;
    private javax.swing.JLabel jLbl_robotGIF;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
